backend:
  name: github
  repo: rahulsrivathsa/rahulsrivathsa-website
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "thoughts"
    label: "Blog Posts"
    folder: "_thoughts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}